import { useState } from 'react'
import ResearchAssistant from './ResearchAssistant'
import { getResearchFacts } from './researchInsights'

const tabs = ['Overview', 'Patient Timeline', 'Signals', 'Cohort', 'Research Assistant']
const statusName = { stable: 'Stable', watch: 'Watch', needs_attention: 'Needs attention' }
export default function ResearcherShell({ timeline, twin }) {
  const [tab, setTab] = useState('Overview')
  const facts = getResearchFacts(timeline, twin)
  return <main className="researcher-shell"><div className="page-width"><div className="researcher-top"><p className="eyebrow">RESEARCHER VIEW · DEMO SHELL</p><h1>Signals across<br /><em>the journey.</em></h1><p>Longitudinal patient modeling will connect here. Current views show structured simulated check-ins only.</p></div><nav className="app-tabs research-tabs" aria-label="Researcher sections">{tabs.map((name) => <button type="button" key={name} aria-current={tab === name ? 'page' : undefined} className={tab === name ? 'active' : ''} onClick={() => setTab(name)}>{name}</button>)}</nav>
    {tab !== 'Research Assistant' && <div className="tab-stage researcher-stage" key={tab}>
      {tab === 'Overview' && <section className="research-panel"><p className="eyebrow">AT A GLANCE</p><h2>Researcher intelligence,<br /><em>ready for integration.</em></h2><div className="research-stat-row"><div><span>DEMO PATIENT</span><strong>Maya</strong></div><div><span>CURRENT WEEK</span><strong>{twin?.current_week ?? '—'} / 4</strong></div><div><span>TWIN STATUS</span><strong>{statusName[facts.status]}</strong></div><div><span>RECORDED CHECK-INS</span><strong>{facts.reports.length}</strong></div></div><p className="research-provenance">Synthetic profile · simulated check-ins · no researcher model connected</p></section>}
      {tab === 'Patient Timeline' && <section className="research-panel"><p className="eyebrow">PATIENT TIMELINE</p><h2>Maya, week by week.</h2><p className="research-description">Weekly visits are simulated. Entries below reflect submitted demo check-ins.</p><div className="research-week-list">{(timeline?.weeks || []).map((week) => <div key={week.week}><span className="research-week-number">0{week.week}</span><div><strong>Week {week.week}</strong><p>{week.visit?.title} · Simulated visit</p></div><div className="research-week-values">{week.checkin ? <>Wellbeing {week.checkin.overall_wellbeing}/10 · Fatigue {week.checkin.fatigue ?? '—'}/10 · Mood {week.checkin.mood || '—'}<small>Simulated patient report</small></> : <span>No check-in submitted</span>}</div></div>)}</div></section>}
      {tab === 'Signals' && <section className="research-panel"><p className="eyebrow">SIGNALS · DEMO DERIVED</p><h2>What changed?</h2><p className="research-description">Simple comparisons from recorded values. No alert model or clinical interpretation is connected.</p><div className="research-signal-grid"><div><span>CURRENT TWIN STATUS</span><strong>{statusName[facts.status]}</strong><p>Demo status heuristic from the patient twin.</p></div><div><span>RECORDED WORSENING</span><strong>{facts.worsening.length ? `${facts.worsening.length} value${facts.worsening.length > 1 ? 's' : ''}` : 'None identified'}</strong><p>{facts.reports.length < 2 ? 'Two check-ins are needed for change detection.' : facts.worsening.map((item) => `${item.name} ${item.from} → ${item.to}`).join(', ') || 'No tracked values worsened.'}</p></div><div><span>PATIENT ALERTS</span><strong>Awaiting integration</strong><p>Crystal's longitudinal alerts are not connected.</p></div></div></section>}
      {tab === 'Cohort' && <section className="research-panel"><p className="eyebrow">COHORT · PLACEHOLDER</p><h2>The wider picture<br /><em>comes next.</em></h2><p className="research-description">Cohort trends and comparisons will appear when Crystal's researcher pipeline is integrated. No cohort statistics are generated from this single demo patient.</p><div className="cohort-placeholder"><span>✳</span><strong>Awaiting cohort integration</strong><p>Reserved for verified aggregate trends and longitudinal summaries.</p></div></section>}
    </div>}
    <div hidden={tab !== 'Research Assistant'} className="tab-stage researcher-stage"><ResearchAssistant timeline={timeline} twin={twin}/></div>
  </div></main>
}
